# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.134.1/containers/debian/.devcontainer/base.Dockerfile
ARG VARIANT="buster"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
RUN apt-get update && apt-get -y install pandoc texlive texlive-generic-recommended




